# Settings

# Bind Ctrl-a as prefix
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Sensible pane splitting
bind | split-window -h 
bind - split-window -v
unbind '"'
unbind '%'

# Fast pane switching
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Enable mouse mode (tmux 2.1 and above)
set -g mouse on

# Don't rename windows automatically
set-option -g allow-rename off

# Count numbers from 1 not 0
set -g base-index 1
setw -g pane-base-index 1

# Maximize window
setw -g aggressive-resize on

# Reload tmux config                                                             
bind r source-file ~/.tmux.conf \; display "Reloaded tmux config!"

# Set default terminal
set-option -g default-terminal "screen-256color"

# Set terminal colours
set-option -sa terminal-overrides ",xterm-256color:RGB"
#set-option -ga terminal-overrides ",xterm-256color:Tc"

# Increase key response time
set -s escape-time 0

# Options from default config saved in .tmux.conf.bcup
# run "tmux show -g | sed 's/^/set -g /' > ~/.tmux.conf"

# 
set -g default-shell "/bin/bash"
set -g default-size "160x48"
set -g history-limit 10000

# Powerline
source "/usr/share/tmux/powerline.conf"

# Plugins

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-yank'
#set -g @plugin 'tmux-plugins/tmux-urlview'
#set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-logging'
set -g @plugin 'tmux-plugins/tmux-sessionist'
set -g @plugin 'tmux-plugins/tmux-sidebar'
#set -g @plugin 'jbnicolai/tmux-fpp'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
