# $XDG_CONFIG_HOME/alacritty/conf.d/hints.toml

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
hyperlinks = true
command = "xdg-open"
post_processing = true
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
