# $XDG_CONFIG_HOME/alacritty/conf.d/window.toml

[window]
dimensions = { columns = 120, lines = 30 }
padding = { x = 4, y = 4 }
dynamic_padding = true
decorations = "full"
opacity = 1.0
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true

[window.class]
instance = "Alacritty"
general = "Alacritty"
