# $XDG_CONFIG_HOME/alacritty/fonts/inconsolata.toml

[font]
normal = { family = "Inconsolata Nerd Font", style = "Regular" }
bold = { family = "Inconsolata Nerd Font", style = "Bold" }
italic = { family = "Inconsolata Nerd Font", style = "Italic" }
bold_italic = { family = "Inconsolata Nerd Font", style = "Bold Italic" }
size = 11.0
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

builtin_box_drawing = true
