# ~/.config/alacritty/fonts/jetbrains-mono.toml

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 11.0
offset = { x = 0, y = 2 }
glyph_offset = { x = 0, y = 1 }

builtin_box_drawing = true
